name: Code analysis

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        php: ['8.2', '8.3']
    runs-on: ubuntu-latest
    name: PHP ${{ matrix.php }}
    
    steps:
    - uses: actions/checkout@v3
      
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        extensions: mbstring, intl, json
        coverage: pcov
        tools: composer:v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Run PHP lint
      run: find . -name \*.php ! -path "./.Build/*" | xargs -n1 php -d display_errors=stderr -l

    - name: Install composer dependencies
      run: |
        cd .Build/
        composer install --no-progress

    - name: Validate PHP coding guidelines
      run: |
        .Build/vendor/bin/php-cs-fixer fix --config=.Build/php-cs-fixer/.php-cs-fixer.php -v --dry-run --stop-on-violation --using-cache=no
